### ISSUE TITLE
GET myUrl//main.min.js 404 (Not Found)

### ISSUE THREAD

**Issue by chilzyj** [PaulKinlan/qrcode#17]
Excuse me, I've got some problem when build and learn your project.
After I run the project by "gulp serve" at local, nether can asking from desktop web or app web got the camera.
Error is like:
GET http://my-url/scripts/main.min.js 404 (Not Found)
my-url/:1 Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
What can be the result?Thanks!

**Comment by chilzyj** [comment]
Well...I‘d find the fire main.min.js and drop it into the 'script' folder....
It works.But I'm not sure is this method correct.

**Comment by PaulKinlan** [comment]
I would suggest using gulp serve:dist
