### ISSUE TITLE
Mirror the screen

### ISSUE THREAD

**Issue by edent** [PaulKinlan/qrcode#2]
As a user, I expect the display to act like a mirror. 

If my QR is too far to the left of the screen, I expect that I have to move my hand to the right.  At the moment, if I move right, the image on screen moves _further to the left!_

**Comment by edent** [comment]
This can be accomplished by adding `transform: scale(-1, 1);` to the CSS of `id="qr-canvas"`

**Comment by PaulKinlan** [comment]
This is on desktop?

**Comment by PaulKinlan** [comment]
Or at least user-facing camera?

**Comment by PaulKinlan** [comment]
(I think your idea makes sense btw)

**Comment by edent** [comment]
Yes, on desktop/laptop - or any Front Facing Camera :-)

**Comment by PaulKinlan** [comment]
Takes a couple of minutes for the SW to update the page correctly.

**Comment by monteslu** [comment]
I think this broke again.  It's not mirrored for the front camera
