### ISSUE TITLE
Native BarcodeDetector throws error in Chrome 59

### ISSUE THREAD

**Issue by BairDev** [PaulKinlan/qrcode#25]
When I'm trying this [application](https://qrsnapper.appspot.com/) with `chrome://flags/#enable-experimental-web-platform-features` turned on I only see, that this error is thrown:

    err; // -> DOMException: Failed to get pixels for current frame.
    err.code; // -> 11
    err.message; // -> "Failed to get pixels for current frame."
    err.name; // -> "InvalidStateError"

The code of the application under this URL might be out of date and Google Analytics might has shown this error already. But I wanted to let you know.

**Edit** Oh, didn't see, that [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=714927) has been filed already.

---

Turning off the experimental web platform features and using the polyfill does not work either, though. But there is certainly a different reason for this.

**Comment by PaulKinlan** [comment]
This should work now.
