### ISSUE TITLE
did not work offline

### ISSUE THREAD

**Issue by kzahel** [PaulKinlan/qrcode#4]
I have a Moto G3 and used the app about a month ago.
I added it to my homescreen
I tried to open it today while offline, and I get an error "This webpage is not available - ERR_FAILED"

Wasn't it supposed to work offline? Is this an issue of chrome clearing its local serviceworker cache?

**Comment by PaulKinlan** [comment]
Hmmm. I'll check. "It should" work

**Comment by bom64** [comment]
After a year - have you found out if it is working offline? Else change the info on chrome webstore saying it is not working offline.

**Comment by PaulKinlan** [comment]
I've just tested it again and it works for me.  I am making some updates today so I will see if that helps you.
