### ISSUE TITLE
Chrome and upload option

### ISSUE THREAD

**Issue by Razorholt** [PaulKinlan/qrcode#42]
Hi Paul!
When I use Chrome on iPhone (OS 11.3) I get the upload button option, which is expected. I am able to launch the camera and take a picture but then it goes back to the initial page:
![img_5974](https://user-images.githubusercontent.com/5605177/36345688-5b3adf9c-13f5-11e8-864f-ef418200ab4e.PNG)

Is that normal? Where is that photo stored? Maybe I could upload it and decode the qr code at the server level?

**Comment by PaulKinlan** [comment]
It is just uploaded to the browser, the decode should be able to take place all via JS in the browser... note, that this should work fine now in Safari.
