### ISSUE TITLE
Will fail when GA is blocked

### ISSUE THREAD

**Issue by emilbjorklund** [PaulKinlan/qrcode#47]
Not a huge deal, but was struggling with demo until I got the chance to hook up my iOS phone to Safari devtools and see what was going on. I have a content blocker which was blocking GA tracking, and snapping a code leads to `Unhandled Promise Rejection: ReferenceError: Can't find variable: ga`.

**Comment by PaulKinlan** [comment]
ah. Good spot. Will sort.

**Comment by PaulKinlan** [comment]
I originally had thought about this by gating 'ga' call because in China it took an age to resolve, but I didn't gate it correctly in strict mode.
