### ISSUE TITLE
Live camera view no longer working on iOS

### ISSUE THREAD

**Issue by rdarcy1** [PaulKinlan/qrcode#57]
It appears that you're no longer able to use the live camera feed to detect codes on iOS devices – something to do with an update to the camera API maybe?

![IMG_388DC15850A8-1](https://user-images.githubusercontent.com/15962421/56359475-94937500-61d9-11e9-8ac2-31170cff3f82.jpeg)

Tested on iPhone 7, X, Xs; Safari and Firefox.
All running iOS 12.

**Comment by Crisfole** [comment]
We fixed this by adding `muted autoplay playsinline` on the `video` element.

**Comment by rdarcy1** [comment]
@Crisfole aren't those attributes already on the video element? https://github.com/PaulKinlan/qrcode/blob/production/app/index.html#L45

I've had some success by switching the `getUserMedia` API to use the [navigator.MediaDevice](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) object, but as the two don't adhere to the same interface it requires some deeper code changes.

**Comment by Crisfole** [comment]
Sorry, I just realized we'd switched to a wrapper of qr-reader...wrong repo.
